#Problem set 3

##P1, P2, P3, P4 Diamonds
```{r}
library(ggplot2)
data(diamonds)
#P1
names(diamonds)
dim(diamonds)
str(diamonds)
levels(diamonds$color)
?diamonds

#P2
qplot(data = diamonds, x = price)

#P3
summary(diamonds$price)

#P4
dim(subset(diamonds, price <500))
dim(subset(diamonds, price <250))
dim(subset(diamonds, price >=15000))

#P5

qplot(data = diamonds, x = price) +
  scale_x_continuous(limits = c(0,2500))

qplot(data = diamonds, x = price) +
  scale_x_continuous(limits = c(500,1000))

qplot(data = diamonds, x = price) +
  scale_x_continuous(limits = c(700,900))

qplot(data = diamonds, x = price, binwidth=1) +
  scale_x_continuous(limits = c(250,2500), breaks=seq(250,2500,250))
ggsave("diamonddetail.png")

#P6
qplot(data = diamonds, x = price) +
  facet_wrap(~cut)

#p7
by(diamonds$price, diamonds$cut, max)
by(diamonds$price, diamonds$cut, min)
by(diamonds$price, diamonds$cut, median)

#p8
qplot(x = price, data = diamonds) + facet_wrap(~cut)

?facet_wrap

##different y scales for facet wrapped plots
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales="free_y")

#p9
# Create a histogram of price per carat
# and facet it by cut.

# Adjust the bin width and transform the scale
# of the x-axis using log10.

qplot(x = price, data = diamonds, binwidth=.01) + facet_wrap(~cut) +
  scale_x_log10()

#p10
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.
qplot(x = clarity, y = price, data = diamonds, geom = "boxplot")

qplot(x = clarity, y = price, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(0,7500))

qplot(x = clarity, y = price, 
      data = subset(diamonds,diamonds$carat==1)
      , geom = "boxplot")

by(diamonds$price, diamonds$clarity, summary)
by(diamonds$price, diamonds$clarity, max)
by(diamonds$price, diamonds$clarity, median)

#p11
#Price range for middle 50% of diamonds with color D
summary(diamonds$price[diamonds$color=="D"])
#Price range for middle 50% of diamonds with color J
summary(diamonds$price[diamonds$color=="J"])
#IQR for diamonds with best color (D)
IQR(diamonds$price[diamonds$color=="D"])
#IQR for diamonds with worst color (J)
IQR(diamonds$price[diamonds$color=="J"])

#p12
# Investigate the price per carat of diamonds across
# the different colors of diamonds using boxplots.

#first pass
qplot(x = color, y = price, data = diamonds, geom = "boxplot")
#oddly, worst color(J has highest median price)

#control for size
#at one carat
qplot(x = color, y = price, data = diamonds[diamonds$carat==1,], geom = "boxplot")

#btwn 1 and 2
qplot(x = color, y = price, 
      data = subset(diamonds, diamonds$carat>1 & diamonds$carat<=2), 
      geom = "boxplot")

#btwn 2 and 3
qplot(x = color, y = price, 
      data = subset(diamonds, diamonds$carat>2 & diamonds$carat<=3), 
      geom = "boxplot")
#Here color seems to have more of the expected effect

#>3
qplot(x = color, y = price, 
      data = subset(diamonds, diamonds$carat>3), 
      geom = "boxplot")
#J has highest median. maybe at this size, color doesn't really matter

#unless- clarity?
qplot(x = color, y = price, 
      data = diamonds, 
      geom = "boxplot") + 
  facet_wrap(~clarity)

qplot(x = color, y = price, 
      data = subset(diamonds, diamonds$carat<1), 
      geom = "boxplot") + 
  facet_wrap(~clarity)

#p13
#investigate weight of diamonds with a frequency polygon

qplot(x = carat, data = diamonds, binwidth = 0.1, geom = "freqpoly") +
  scale_x_continuous(limits = c(0,3), breaks = seq(0,3,.1))

qplot(x = carat, data = diamonds, binwidth = 0.01, geom = "freqpoly") +
  scale_x_continuous(limits = c(0,2), breaks = seq(0,2,.1))
```
##Gapminder data
```{r}
#p14 - resume here
```

